/**
 * 位置屬性定義
 *
 * 70+ 種位置屬性與欄位定義。
 * 對應 FRONTME.md 14.7 usePositionAttributes 章節。
 */

import type { AttributeDef } from './useDeviceAttributes';

/** 位置屬性 */
export const usePositionAttributes = (t: (key: string) => string): AttributeDef[] => [
  { key: 'id', name: 'ID', type: 'number' },
  { key: 'deviceId', name: 'Device ID', type: 'number' },
  { key: 'protocol', name: 'Protocol', type: 'string' },
  { key: 'deviceTime', name: 'Device Time', type: 'string' },
  { key: 'fixTime', name: 'Fix Time', type: 'string' },
  { key: 'serverTime', name: 'Server Time', type: 'string' },
  { key: 'valid', name: 'Valid', type: 'boolean' },
  { key: 'latitude', name: 'Latitude', type: 'number' },
  { key: 'longitude', name: 'Longitude', type: 'number' },
  { key: 'altitude', name: 'Altitude', type: 'number' },
  { key: 'speed', name: 'Speed', type: 'number' },
  { key: 'course', name: 'Course', type: 'number' },
  { key: 'address', name: 'Address', type: 'string' },
  { key: 'accuracy', name: 'Accuracy', type: 'number' },
  { key: 'geofenceIds', name: 'Geofence IDs', type: 'string' },
  { key: 'odometer', name: 'Odometer', type: 'number' },
  { key: 'serviceOdometer', name: 'Service Odometer', type: 'number' },
  { key: 'tripOdometer', name: 'Trip Odometer', type: 'number' },
  { key: 'hours', name: 'Hours', type: 'number' },
  { key: 'steps', name: 'Steps', type: 'number' },
  { key: 'heartRate', name: 'Heart Rate', type: 'number' },
  { key: 'batteryLevel', name: 'Battery Level', type: 'number' },
  { key: 'charge', name: 'Charging', type: 'boolean' },
  { key: 'rpm', name: 'RPM', type: 'number' },
  { key: 'fuelConsumption', name: 'Fuel Consumption', type: 'number' },
  { key: 'fuelLevel', name: 'Fuel Level', type: 'number' },
  { key: 'fuelTemp', name: 'Fuel Temperature', type: 'number' },
  { key: 'coolantTemp', name: 'Coolant Temperature', type: 'number' },
  { key: 'engineTemp', name: 'Engine Temperature', type: 'number' },
  { key: 'throttle', name: 'Throttle', type: 'number' },
  { key: 'obdSpeed', name: 'OBD Speed', type: 'number' },
  { key: 'obdOdometer', name: 'OBD Odometer', type: 'number' },
  { key: 'driverUniqueId', name: 'Driver Unique ID', type: 'string' },
  { key: 'image', name: 'Image', type: 'string' },
  { key: 'video', name: 'Video', type: 'string' },
  { key: 'audio', name: 'Audio', type: 'string' },
  { key: 'input1', name: 'Input 1', type: 'number' },
  { key: 'input2', name: 'Input 2', type: 'number' },
  { key: 'input3', name: 'Input 3', type: 'number' },
  { key: 'input4', name: 'Input 4', type: 'number' },
  { key: 'output1', name: 'Output 1', type: 'number' },
  { key: 'output2', name: 'Output 2', type: 'number' },
  { key: 'output3', name: 'Output 3', type: 'number' },
  { key: 'output4', name: 'Output 4', type: 'number' },
  { key: 'adc1', name: 'ADC 1', type: 'number' },
  { key: 'adc2', name: 'ADC 2', type: 'number' },
  { key: 'adc3', name: 'ADC 3', type: 'number' },
  { key: 'adc4', name: 'ADC 4', type: 'number' },
  { key: 'hdop', name: 'HDOP', type: 'number' },
  { key: 'vdop', name: 'VDOP', type: 'number' },
  { key: 'pdop', name: 'PDOP', type: 'number' },
  { key: 'sat', name: 'Satellites', type: 'number' },
  { key: 'satVisible', name: 'Visible Satellites', type: 'number' },
  { key: 'rssi', name: 'RSSI', type: 'number' },
  { key: 'gps', name: 'GPS', type: 'number' },
  { key: 'roaming', name: 'Roaming', type: 'boolean' },
  { key: 'event', name: 'Event', type: 'number' },
  { key: 'alarm', name: 'Alarm', type: 'string' },
  { key: 'status', name: 'Status', type: 'string' },
];
